### ISSUE TITLE
Extension icons aren't vertically aligned in /manage/publishers/<publisher>

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vsmarketplace#12]
On https://marketplace.visualstudio.com/manage/publishers/tyriar, see how the icons aren't center aligned like the text

![image](https://user-images.githubusercontent.com/2193314/109886117-73ed3080-7c34-11eb-976a-5e065df4dc05.png)

This CSS rule fixes the problem:

```css
.vss-DetailsList.ms-DetailsList .ms-List-cell .ms-DetailsRow .vss-DetailsList--titleCellIcon {
    align-items: center;
}
```

![image](https://user-images.githubusercontent.com/2193314/109886292-af87fa80-7c34-11eb-8866-d463aec44da2.png)
